### ISSUE TITLE
error - cutting into non-free mapping

### ISSUE THREAD

**Issue by adamantinum** [maharmstone/quibble#29]
Hi,
Initially I continued the ReactOS issue, but I find the same error on Windows XP, so I'm opening a new one.
I installed Windows XP on a MBR disk, then I converted it to GPT, added an EFI partition and converted NTFS in BTRFS with your tool. Sadly quibble returned the error in the title. A similar things happened on ReactOS. I installed it on BTRFS (MBR disk, ROS doesn't support GPT yet), added an EFI partition and tried to boot with quibble.
The systems are virtualized on qemu and as firmware I used OVMF with CSM support, built for 32bit.
I link a screenshot, hoping it could be useful.
![Schermata del 2020-10-14 16-13-02](https://user-images.githubusercontent.com/50221095/96009602-24eb5e00-0e41-11eb-99ec-34be5323d9ce.png)

**Comment by yurikoles** [comment]
Please consult [MS FAQ on GPT](https://docs.microsoft.com/en-us/previous-versions/windows/hardware/design/dn640535(v=vs.85)#answers-about-windows-disk-support). 
In two words: WinXP x86 doesn't support GPT disks. Later versions support it. But conversion after installation isn't supported. In order to install/boot Windows from GPT disk you need to boot installer in UEFI mode. And vise versa: in order to install and boot from MBR disk you need to boot installer in BIOS or UEFI CSM mode.

**Comment by adamantinum** [comment]
I tried also with Windows XP on MBR, but the issue is the same...

**Comment by maharmstone** [comment]
@yurikoles - I can't remember the specifics, as it's been a while, but I think I proved that at least some parts of that are bullshit. Microsoft were claiming that e.g. it was impossible to use MBR partitions in UEFI mode, but what they really meant was that they couldn't be bothered putting it in the bootloader.

@adamantinum - hopefully this is fixed by https://github.com/maharmstone/quibble/commit/c657723480343cbeb056ee6d8284357a31d254a0.

**Comment by adamantinum** [comment]
Thank you, I'll try!

**Comment by adamantinum** [comment]
First of all, thank you for your work!
I compiled at the last commit, but the issue is still present.

**Comment by schreiberstein** [comment]
Issue is still present.
Tested on VMware.
Hybrid MBR/GPT, Windows XP i386 with installed WinBtrfs.
Would appreciate if you could fix it for us Retro folks.

Merry Christmas 
schreiberstein

**Comment by maharmstone** [comment]
Thanks @schreiberstein. I think the issue is essentially that Windows is far too tolerant of dirty NTFS volumes. Possibly I need to change it so we calculate a free-space bitmap manually, as what's stored on the disk is evidently a load of rubbish...
